# -*- coding: utf-8 -*-
"""Exercicios_continuando_c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YcUNHvKnun9XWk5mgopnPRBbUiFi6ZYE

#União de Conjuntos - Números de 1 a 10 e de 5 a 15

Crie duas listas, uma contendo os números de 1 a 10 e outra contendo os números de 5 a 15. Em seguida, transforme essas listas em conjuntos e realize a união entre eles. Por fim, exiba o resultado da união dos conjuntos.
"""

numeros110 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numeros515 = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

uniao = numeros110.copy()
uniao.extend(numeros515)
set(uniao)

"""as duas opções são validas"""

numeros110 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
numeros515 = {5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}

uniao = numeros110 | numeros515
print(uniao)

"""# Encontre os números pares únicos em uma lista

Escreva um programa em Python que recebe uma lista de números inteiros como entrada e retorna um conjunto contendo apenas os números pares da lista, sem repetições.

Você pode começar criando uma lista de números inteiros e, em seguida, utilizar os conceitos de conjuntos vistos na aula para filtrar os números pares e remover as repetições.
"""

numeros = [1, 5, 10, 15, 20, 25, 30]

par = [numero for numero in numeros if numero % 2 == 0]
impar = [numero for numero in numeros if not numero % 2 == 0]
print(impar)
print(par)

"""# Contador de Letras em uma Frase

Escreva um programa em Python que conte a quantidade de vezes que cada letra aparece em uma frase. Utilize um dicionário para armazenar as letras como chaves e as contagens como valores. Por exemplo, para a frase "Alura é demais", o programa deve retornar o seguinte dicionário: {'A': 1, 'l': 1, 'u': 1, 'r': 1, 'a': 1, ' ': 2, 'é': 1, 'd': 1, 'e': 1, 'm': 1, 'i': 1, 's': 1}.


"""

palavras = "Alura é demais"
dicionario = {}

def valores_contagem():
  for palavra in palavras.split():
    for letra in palavra.lower():
      if letra in dicionario:
            dicionario[letra] += 1
      else:
            dicionario[letra] = 1
  return dicionario
valores_contagem()

palavras = "Alura é demais"
dicionario = {}

def valores_contagem():
  for palavra in palavras.split():
      if palavra.lower() in dicionario:
            dicionario[palavra] += 1
      else:
            dicionario[palavra] = 1
  return dicionario
valores_contagem()

palavras = "Alura é demais"
dicionario = {}

def valores_contagem():
  for palavra in palavras.split():
    for letra in set(palavra.lower()):
      if letra in dicionario:
            dicionario[letra] += 1
      else:
            dicionario[letra] = 1
  return dicionario

valores_contagem()

"""# Controle de Estoque

Crie um dicionário chamado "estoque" com os seguintes itens e suas respectivas quantidades: "banana" (10), "maçã" (5), "laranja" (8), "abacaxi" (3).

Em seguida, faça as seguintes operações:

* Adicione mais 5 unidades de "banana" ao estoque.
* Substitua a quantidade de "maçã" por 7 unidades.
* Remova o item "abacaxi" do estoque.
* Verifique se "laranja" está presente no estoque.
* Itere sobre as chaves do estoque e imprima cada uma delas.
* Utilize o método values() para obter um iterável contendo as quantidades do estoque e imprima cada uma delas.
* Utilize o método items() para obter um iterável contendo as chaves e valores do estoque e imprima cada um deles.
* Utilize um list comprehension para criar uma lista de strings contendo as chaves do estoque concatenadas com a palavra " - estoque: " e suas respectivas quantidades.
"""

estoque = {
    "banana": 10,
    "maçã": 5,
    "laranja": 8,
    "abacaxi": 3
}

def adicionar_produto_estoque(produto, valor):
    if produto in estoque:
      estoque[produto] += valor
      print("Foi adicionado {} em {}".format(valor, produto))

def substituir_estoque(produto, valor):
  if produto in estoque:
      estoque[produto] = valor
      return print("Foi substituido {} em {}".format(valor, produto))

def verifica_quantidade(produto):
    if produto in estoque:
      print("Produto: {} - Quantidade: {}".format(produto, estoque[produto]))
      return

def total_estoque():
  print(sum(estoque.values()))

def quantidade_verificada_total():
  for produto, quantidade in estoque.items():
    print(f"Produto: {produto} - Quantidade: {quantidade}")

def procurar_produto(produto):
    if produto in estoque:
       print(f"Produto: {produto} encontrado")
    else:
       print("não encontrado {}".format(produto))

def remove_produto(produto):
  if produto in estoque:
    del estoque[produto]
    print("Produto: {} deletado".format(produto))
  else:
    print("não encontrado {}".format(produto))

print(estoque)

"""# Contador de Palavras usando defaultdict

Um exercício interessante seria criar uma função que recebe um texto como parâmetro e retorna um dicionário com a contagem de aparições de cada palavra no texto. Você pode pedir para o usuário inserir um texto ou utilizar um texto fixo para testar a função. Lembre-se de utilizar o defaultdict para facilitar a contagem das palavras. Experimente criar essa função e testar com diferentes textos
"""

from posixpath import split
from collections import defaultdict

meu_texto = "Python é uma linguagem de programação muito utilizada em análise de dados e machine learning. A simplicidade e legibilidade do Python a tornam uma ótima escolha para cientistas de dados e desenvolvedores."
meu_texto = meu_texto.lower()

aparicoes = defaultdict(int)

for palavras in meu_texto.split():
  ate_agora = aparicoes[palavras]
  aparicoes[palavras] = ate_agora + 1

aparicoes

"""# Contador de Letras utilizando o Counter"""

from collections import Counter

meu_texto = "O rato roeu a roupa do rei de Roma"
meu_texto = meu_texto.lower()

aparicoes = Counter(meu_texto.split())
aparicoes

"""# Contador de Palavras Excluindo Palavras Comuns

Que tal tentar implementar um contador de palavras que desconsidere as palavras comuns, como artigos e preposições? Isso pode ser feito utilizando o Counter em conjunto com uma lista de palavras a serem desconsideradas. Tente implementar essa lógica e veja como fica!
"""

from collections import Counter


palavras_comuns = ["o", "a", "de", "para", "com", "em", "um", "uma", "se", "por", "no", "na", "nos", "nas", "ao", "à", "às", "do", "da", "dos", "das", "que", "como", "quando", "onde", "porque", "quem", "qual", "quais", "entre", "sobre", "sob", "através", "até", "após", "ante", "perante", "sem", "sob", "sobre", "trás"]

meu_texto = "O cachorro é um animal de estimação muito comum. Os cachorros são conhecidos por sua lealdade e companheirismo. Muitas pessoas têm um cachorro como animal de estimação. O cachorro é considerado o melhor amigo do homem."
meu_texto = meu_texto.lower()

aparicoes = Counter(meu_texto.split())

for comum in palavras_comuns:
  if comum in aparicoes:
    del aparicoes[comum]

print(aparicoes)

"""# Análise de Frequência de Letras em um Texto

 Um exercício interessante seria criar uma função que recebe um texto como parâmetro e retorna as 10 letras mais frequentes, juntamente com a porcentagem de ocorrência de cada uma delas. Você pode utilizar o método Counter para contar a frequência de cada letra no texto e, em seguida, calcular a porcentagem de ocorrência.
"""

meu_texto = "Python é uma linguagem de programação de alto nível, interpretada, de script, imperativa, orientada a objetos, funcional, de tipagem dinâmica e forte. Foi lançada por Guido van Rossum em 1991."

from collections import Counter

def analisa_frequencia_de_letras(texto):
  aparicoes = Counter(texto.lower())
  total_caracteres = sum(aparicoes.values())

  proporcoes = [(letra, frequencia / total_caracteres) for letra, frequencia in aparicoes.items()]
  proporcoes = Counter(dict(proporcoes))
  letras_comum = proporcoes.most_common(10)
  for caractere, proporcao in letras_comum:
    print("{} => {:.2f}%".format(caractere, proporcao * 100))

analisa_frequencia_de_letras(meu_texto)

"""Contagem de Frequência de Palavras em um Texto"""

texto1 = """A área de Análise e Desenvolvimento de Sistemas é centrada na criação e implementação de soluções de software para atender às necessidades dos usuários e das organizações. Os profissionais dessa área estão constantemente envolvidos na análise de requisitos, no design de sistemas, na codificação de programas e na realização de testes para garantir a qualidade do software produzido.

Os analistas e desenvolvedores de sistemas trabalham com uma variedade de linguagens de programação, frameworks e tecnologias, adaptando-se às demandas do projeto e às preferências da equipe. Eles colaboram de perto com outros profissionais de TI e com as partes interessadas do negócio para garantir que as soluções desenvolvidas atendam aos objetivos e requisitos definidos.

Essa área oferece uma ampla gama de oportunidades de carreira, desde desenvolvedores de software que se concentram na codificação e na implementação técnica até analistas de sistemas que desempenham um papel mais estratégico na identificação de necessidades e na definição de requisitos de software. """

texto2 = """A Gestão da Tecnologia da Informação é uma disciplina que se concentra na liderança e na administração dos recursos de TI de uma organização. Os profissionais de Gestão de TI são responsáveis por definir a estratégia de tecnologia da informação, gerenciar equipes de TI, supervisionar projetos de tecnologia e garantir que os recursos de TI sejam utilizados de forma eficiente para apoiar os objetivos de negócio da organização.

Eles lidam com uma variedade de áreas, incluindo infraestrutura de TI, segurança da informação, governança de TI, gestão de serviços de TI e gestão de projetos de TI. Além disso, eles estão frequentemente envolvidos na avaliação e na implementação de novas tecnologias para melhorar a eficiência operacional e a competitividade da empresa.

Os gestores de TI precisam ter habilidades técnicas sólidas, bem como habilidades de liderança e comunicação, para garantir o sucesso dos projetos de TI e alinhar as iniciativas de tecnologia com as metas estratégicas da organização. Esta área oferece oportunidades para indivíduos que estão interessados tanto na tecnologia quanto na gestão de negócios."""

from collections import Counter
from posixpath import split

def analisa_frequencia_de_palavras(texto):
  texto = texto.lower()
  aparicoes = Counter(texto.split())
  total_de_palavras = sum(aparicoes.values())

  proporcoes = [(palavra, frequencia / total_de_palavras) for palavra, frequencia in aparicoes.items()]
  proporcoes = Counter(dict(proporcoes))

  palavras_comuns = proporcoes.most_common(10)

  for palavras, aparicao in palavras_comuns:
     print("{} => {:.2f}%".format(palavras, aparicao * 100))

analisa_frequencia_de_palavras(texto1)